Class {
	#name : #DosteABBNode,
	#superclass : #Object,
	#instVars : [
		'data',
		'left',
		'right'
	],
	#category : #'2tDataStructures'
}

{ #category : #accessing }
DosteABBNode >> data [

	^ data
]

{ #category : #accessing }
DosteABBNode >> data: anObject [

	data := anObject
]

{ #category : #accessing }
DosteABBNode >> left [

	^ left
]

{ #category : #accessing }
DosteABBNode >> left: anObject [

	left := anObject
]

{ #category : #accessing }
DosteABBNode >> right [

	^ right
]

{ #category : #accessing }
DosteABBNode >> right: anObject [

	right := anObject
]
